package com.mydirectory.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@DynamoDBTable(tableName = "Clients")
@Getter
@Setter
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Generic {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String json;

}
